### PR TITLE
Execute a shell command when backup is complete

### PR DESCRIPTION
**Pull request by auricom**
Hello,

I would like the backup script to execute a shell command when backup is complete (in my case, a webhook to a [cron monitoring tool](https://github.com/healthchecks/healthchecks)).

I added a new environment variable so a user can define its own custom hook shell command.

Thanks for considering this.

### CODE REVIEW

**Review by tj57 — APPROVED** [review]
This is a very useful feature

**Comment by prodrigestivill** [comment]
Hello @auricom,

Sorry for the delay.

How would you find to call an external web hook instead of running any arbitrary shell command?

Thanks for your time and the proposal.

**Comment by auricom** [comment]
Hello,

Thanks for considering this feature !

I can replace the arbitrary shell command with a curl, like this :

```
if [ "${WEBHOOK_URL}" != "**None**" ]; then
  echo "Execute post-backup webhook call"

  curl --request POST \
    --url ${WEBHOOK_URL} \
    --max-time 10 \
    --retry 5 \
    ${WEBHOOK_EXTRA_ARGS}
fi
```

This would work in simple uses cases like healthchecks that I use, and people could add further args without too much hassle (e.g : authentication, additional headers...)

I would be happy to make another pull request you think this can be usable.

**Comment by prodrigestivill** [comment]
Merged this PR into main, thanks for your work.

**Comment by prodrigestivill** [comment]
Moved webhook as a separate script hook implementation and also implemented webhook call on error.

**Pull request closed without merging**
